# Generated by Django 3.2.18 on 2023-02-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='image/banner-item-03.jpg', upload_to='uploads/'),
        ),
    ]
