# Generated by Django 3.2.18 on 2023-02-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='uploads/default.jpg', upload_to='uploads/'),
        ),
    ]
