# Generated by Django 3.2.18 on 2023-02-26 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='writer',
        ),
    ]
