# Generated by Django 3.2.18 on 2023-03-07 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_comment_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_date']},
        ),
    ]
