# Generated by Django 3.2.18 on 2023-03-07 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_post_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
