# Generated by Django 3.2.18 on 2023-03-12 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='post',
            name='writer',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
